use std::ffi::{CStr, CString};
use std::os::raw::{c_char, c_int, c_void};

type AllocFn = unsafe extern "C" fn(size: usize, userdata: *mut c_void) -> *mut c_void;
use syntect::easy::HighlightLines;
use syntect::highlighting::{Style, ThemeSet};
use syntect::parsing::SyntaxSet;
use syntect::util::{as_24_bit_terminal_escaped, LinesWithEndings};

pub struct SyntectCtx { ss: SyntaxSet, ts: ThemeSet }

// Auto-generated by build.rs: defines load_extra_themes(ts: &mut ThemeSet).
include!(concat!(env!("OUT_DIR"), "/themes.rs"));

/// Creates a new highlighter context loaded with the built-in syntax and theme sets,
/// plus any extra themes embedded from the `themes/` directory at build time.
///
/// The caller owns the returned pointer and must destroy it with [`syntect_free`] when done.
#[unsafe(no_mangle)]
pub extern "C" fn syntect_new() -> *mut SyntectCtx {
    let mut ts = ThemeSet::load_defaults();
    load_extra_themes(&mut ts);
    Box::into_raw(Box::new(SyntectCtx {
        ss: SyntaxSet::load_defaults_newlines(),
        ts,
    }))
}

/// Destroys a context created by [`syntect_new`] and frees all associated memory.
///
/// Safe to call with a null pointer.
#[unsafe(no_mangle)]
pub extern "C" fn syntect_free(ctx: *mut SyntectCtx) {
    if !ctx.is_null() { unsafe { drop(Box::from_raw(ctx)) }; }
}

/// Highlights `code` and writes the result into a buffer allocated by `alloc`.
///
/// The syntax is selected by matching `extension` (e.g. `"c"`, `"rs"`, `"py"`).
/// If no syntax matches the extension, plain-text is used as a fallback.
///
/// `code` must be valid UTF-8 and does not need to be null-terminated — only the
/// first `code_len` bytes are read. `alloc(size, userdata)` is called exactly once
/// with the required byte count (including the null terminator). The returned pointer
/// is owned by the caller; free it with whatever allocator backs `alloc`.
///
/// Returns null on any error: null pointer argument, `alloc` is null or returns null,
/// unknown `theme_name`, or invalid UTF-8.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn syntect_highlight(
    ctx: *const SyntectCtx, code: *const c_char, code_len: usize,
    extension: *const c_char, theme_name: *const c_char,
    alloc: Option<AllocFn>, userdata: *mut c_void,
) -> *mut c_char {
    let alloc = match alloc { Some(f) => f, None => return std::ptr::null_mut() };
    if ctx.is_null() || code.is_null() || extension.is_null() || theme_name.is_null() {
        return std::ptr::null_mut();
    }
    let ctx   = unsafe { &*ctx };
    let code  = match std::str::from_utf8(unsafe { std::slice::from_raw_parts(code as *const u8, code_len) }) { Ok(s) => s, Err(_) => return std::ptr::null_mut() };
    let ext   = match unsafe { CStr::from_ptr(extension) }.to_str() { Ok(s) => s, Err(_) => return std::ptr::null_mut() };
    let tname = match unsafe { CStr::from_ptr(theme_name) }.to_str() { Ok(s) => s, Err(_) => return std::ptr::null_mut() };
    let syntax = ctx.ss.find_syntax_by_extension(ext)
        .unwrap_or_else(|| ctx.ss.find_syntax_plain_text());
    let theme = match ctx.ts.themes.get(tname) { Some(t) => t, None => return std::ptr::null_mut() };
    let mut hl = HighlightLines::new(syntax, theme);
    let mut out = String::with_capacity(code.len() * 2);
    for line in LinesWithEndings::from(code) {
        let ranges: Vec<(Style, &str)> = match hl.highlight_line(line, &ctx.ss) {
            Ok(r) => r, Err(_) => return std::ptr::null_mut(),
        };
        out.push_str(&as_24_bit_terminal_escaped(&ranges, false));
    }
    out.push_str("\x1b[0m");
    let bytes = out.as_bytes();
    let buf = unsafe { alloc(bytes.len() + 1, userdata) } as *mut c_char;
    if buf.is_null() { return std::ptr::null_mut(); }
    unsafe {
        std::ptr::copy_nonoverlapping(bytes.as_ptr(), buf as *mut u8, bytes.len());
        *buf.add(bytes.len()) = 0;
    }
    buf
}

type ItemCallback = unsafe extern "C" fn(*const c_char, *mut c_void);

/// Calls `cb` once for each available theme name, in case-insensitive sorted order.
///
/// Returns 1 on success, 0 if `ctx` or `cb` is null.
#[unsafe(no_mangle)]
pub extern "C" fn syntect_list_themes(
    ctx: *const SyntectCtx,
    cb: Option<ItemCallback>,
    userdata: *mut c_void,
) -> c_int {
    let Some(cb) = cb else { return 0 };
    if ctx.is_null() { return 0; }
    let ctx = unsafe { &*ctx };
    let mut names: Vec<&str> = ctx.ts.themes.keys().map(|s| s.as_str()).collect();
    names.sort_unstable_by_key(|s| s.to_ascii_lowercase());
    for name in names {
        let s = CString::new(name).unwrap();
        unsafe { cb(s.as_ptr(), userdata) };
    }
    1
}

/// Loads a `.tmTheme` file from disk and registers it under `theme_name`.
///
/// `theme_path` may be an absolute or relative path to the `.tmTheme` file.
/// `theme_name` is the key you pass to [`syntect_highlight`] afterwards.
///
/// Returns 1 on success, 0 on failure (null argument, file not found, invalid format, etc.)
#[unsafe(no_mangle)]
pub extern "C" fn syntect_load_theme(
    ctx:        *mut SyntectCtx,
    theme_path: *const c_char,
    theme_name: *const c_char,
) -> i32 {
    if ctx.is_null() || theme_path.is_null() || theme_name.is_null() {
        return 0;
    }
    let ctx  = unsafe { &mut *ctx };
    let path = match unsafe { CStr::from_ptr(theme_path) }.to_str() {
        Ok(s) => std::path::Path::new(s),
        Err(_) => return 0,
    };
    let name = match unsafe { CStr::from_ptr(theme_name) }.to_str() {
        Ok(s) => s.to_owned(),
        Err(_) => return 0,
    };

    match syntect::highlighting::ThemeSet::get_theme(path) {
        Ok(theme) => {
            ctx.ts.themes.insert(name, theme);
            1
        }
        Err(_) => 0,
    }
}

/// Parses a `.tmTheme` XML string and registers it under `theme_name`.
///
/// `theme_xml` must be a null-terminated string containing the full `.tmTheme` XML.
/// The theme is parsed entirely in memory — no file I/O is performed.
/// `theme_name` is the key you pass to [`syntect_highlight`] afterwards.
///
/// Returns 1 on success, 0 on failure (null argument, invalid XML, bad format, etc.)
#[unsafe(no_mangle)]
pub extern "C" fn syntect_load_theme_str(
    ctx:        *mut SyntectCtx,
    theme_xml:  *const c_char,
    theme_name: *const c_char,
) -> i32 {
    if ctx.is_null() || theme_xml.is_null() || theme_name.is_null() {
        return 0;
    }
    let ctx  = unsafe { &mut *ctx };
    let xml  = match unsafe { CStr::from_ptr(theme_xml) }.to_str() {
        Ok(s) => s,
        Err(_) => return 0,
    };
    let name = match unsafe { CStr::from_ptr(theme_name) }.to_str() {
        Ok(s) => s.to_owned(),
        Err(_) => return 0,
    };

    match ThemeSet::load_from_reader(&mut std::io::Cursor::new(xml.as_bytes())) {
        Ok(theme) => { ctx.ts.themes.insert(name, theme); 1 }
        Err(_)    => 0,
    }
}

/// Calls `cb` once for each supported file extension, in sorted, deduplicated order.
///
/// Returns 1 on success, 0 if `ctx` or `cb` is null.
#[unsafe(no_mangle)]
pub extern "C" fn syntect_list_extensions(
    ctx: *const SyntectCtx,
    cb: Option<ItemCallback>,
    userdata: *mut c_void,
) -> c_int {
    let Some(cb) = cb else { return 0 };
    if ctx.is_null() { return 0; }
    let ctx = unsafe { &*ctx };
    let mut exts: Vec<&str> = ctx.ss.syntaxes().iter()
        .flat_map(|s| s.file_extensions.iter().map(|e| e.as_str())).collect();
    exts.sort_unstable(); exts.dedup();
    for ext in exts {
        let s = CString::new(ext).unwrap();
        unsafe { cb(s.as_ptr(), userdata) };
    }
    1
}
