[package]
name    = "syntect-c"
version = "0.1.0"
edition = "2024"

[lib]
name       = "syntect_c"
crate-type = ["staticlib"]

[dependencies]
syntect = { version = "5.3.0", default-features = false, features = [
    "default-syntaxes",
    "default-themes",
    "regex-onig",
] }

# Favor minimal binary size
# https://doc.rust-lang.org/cargo/reference/profiles.html
[profile.release]
opt-level       = "s"       # Optimize for binary size
lto             = true
codegen-units   = 1
debug           = true      # Embed DWARF/PDB
strip           = "none"
split-debuginfo = "off"     # Keep debug info inside the .a/.lib
panic           = "abort"   # Removes unwind machinery